### ISSUE TITLE
Bitrise build #5

### ISSUE THREAD

**Issue by b23prodtm** [b23prodtm/Provenance#15]
bitrise.io : YML
```
---
format_version: '5'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- push_branch: "*"
  workflow: iOS
- pull_request_source_branch: "*"
  workflow: iOS
workflows:
  iOS:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.11: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.9.3: {}
    - recreate-user-schemes@1.0.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - change-workdir@1.0.1:
        inputs:
        - is_create_path: 'false'
        - path: PVSupport
        is_always_run: true
    - carthage@3.1.4:
        inputs:
        - carthage_options: " --verbose --no-use-binaries --platform iOS --cache-builds"
    - change-workdir@1.0.1:
        inputs:
        - is_create_path: 'false'
        - path: ".."
        is_always_run: true
    - xcode-test@1.18.14:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - deploy-to-bitrise-io@1.3.12: {}
    - cache-push@2.0.5: {}
    envs:
    - opts:
        is_expand: false
      BITRISE_SCHEME: Provenance
    after_run:
    - iOS-deploy
  iOS-deploy:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.11: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.9.3: {}
    - recreate-user-schemes@1.0.2:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - change-workdir@1.0.1:
        inputs:
        - path: PVSupport
    - carthage@3.1.4:
        inputs:
        - carthage_options: " --verbose --no-use-binaries --platform iOS --cache-builds"
    - change-workdir@1.0.1:
        inputs:
        - path: ".."
    - xcode-test@1.18.14:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - xcode-archive@2.4.8:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - export_method: "$BITRISE_EXPORT_METHOD"
    - deploy-to-bitrise-io@1.3.12: {}
    - cache-push@2.0.5: {}
    envs:
    - opts:
        is_expand: false
      BITRISE_SCHEME: Provenance-Release
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: Provenance.xcworkspace
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: development
```

### Expected:  

The following build commands failed:
  CompileC /Users/vagrant/Library/Developer/Xcode/DerivedData/Provenance-gnutbvkfydwnocfjwrhmytsbffaw/Build/Intermediates.noindex/PVYabause.build/Debug-iphonesimulator/PVYabause.build/Objects-normal/x86_64/YabauseGameCore.o YabauseGameCore.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[33;1mIf you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
/Users/vagrant/deploy/raw-xcodebuild-output.log
that will attach the file to your build as an artifact![0m
  - BuildURL: https://app.bitrise.io/build/627e3ab00679efa8
  - /Users/vagrant/deploy/raw-xcodebuild-output.log
[32;1mUploading file: /Users/vagrant/deploy/raw-xcodebuild-output.log[0m
You can find the Artifact on Bitrise, on the Build's page: https://app.bitrise.io/build/627e3ab00679efa8
  - BuildURL: https://app.bitrise.io/build/627e3ab00679efa8
  - /Users/vagrant/deploy/raw-xcodebuild-output.log
[32;1mUploading file: /Users/vagrant/deploy/raw-xcodebuild-output.log[0m
You can find the Artifact on Bitrise, on the Build's page: https://app.bitrise.io/build/627e3ab00679efa8

### Actual:  
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=CocoaLumberjack -fapplication-extension -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wunreachable-code -Wimplicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/CocoaLumberjack-generated-files.hmap -I/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/CocoaLumberjack-own-target-headers.hmap -I/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/CocoaLumberjack-all-non-framework-target-headers.hmap -ivfsoverlay /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/all-product-headers.yaml -iquote /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/CocoaLumberjack-project-headers.hmap -I/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Products/Release-iphonesimulator/include -I/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/DerivedSources/x86_64 -I/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/DerivedSources -F/Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Products/Release-iphonesimulator -include /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/PrecompiledHeaders/CocoaLumberjack-Prefix-gegiqcpcxnhqmkarjosooiuwaert/CocoaLumberjack-Prefix.pch -MMD -MT dependencies -MF /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/Objects-normal/x86_64/DDLog.d --serialize-diagnostics /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/Objects-normal/x86_64/DDLog.dia -c /Users/vagrant/git/PVSupport/Carthage/Checkouts/XCDLumberjackNSLogger/Carthage/Checkouts/CocoaLumberjack/Classes/DDLog.m -o /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/XCDLumberjackNSLogger/1.1.1/Build/Intermediates.noindex/Lumberjack.build/Release-iphonesimulator/CocoaLumberjack-iOS.build/Objects-normal/x86_64/DDLog.o
[31m❌  [0m/Users/vagrant/git/PVYabause/YabauseGameCore.m:216:5: [31mimplicit declaration of function 'DLog' is invalid in C99 [-Werror,-Wimplicit-function-declaration][0m
    DLog(@"Yabause init /debug");
[31m❌  [0m/Users/vagrant/git/PVYabause/YabauseGameCore.m:216:5: [31mimplicit declaration of function 'DLog' is invalid in C99 [-Werror,-Wimplicit-function-declaration][0m
    DLog(@"Yabause init /debug");
	Implicit declaration of function 'DLog' is invalid in C99
```

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [x] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*
- [bitrise build](https://app.bitrise.io/build/627e3ab00679efa8)

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>
